spring.application.name=LarkTalk

spring.datasource.url=jdbc:postgresql://localhost:5432/LarkTalkDB?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
server.port=6789

spring.jpa.hibernate.ddl-auto=update